sonar.projectKey=Leneord1_SWE4713_Group1_SPR2026-1
sonar.organization=leneord1

sonar.sources=frontend/src,api,auth
sonar.tests=frontend/src/__tests__
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.css,**/assets/**,frontend/src/main.jsx
sonar.cpd.exclusions=frontend/api/**

sonar.coverage.exclusions=frontend/src/pages/**,frontend/src/components/**,frontend/src/App.jsx,frontend/src/navbar.jsx,frontend/src/services/Report.js,frontend/src/services/journalService.js,frontend/src/services/ledgerService.js,frontend/src/services/ratioLedgerService.js,frontend/src/services/chartOfAccountsService.js,frontend/src/services/userService.js,frontend/src/services/passwordExpiryNotificationService.js,auth/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
